name: Test with Playwright on JS
on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:
jobs:
  run_test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install pakages
        run: npm install
      - name: Install Playwright 
        run: npx playwright install
      - name: Run tests
        run: npm run test
